### PR TITLE
fix: Added `limits.h` in `data_structures/heap/max_heap.c`

### LINKED ISSUE #758: [BUG] Added limits.h in data_structures/heap/max_heap.c
## Description

bug fixed added limits.h at data_structures/heap/max_heap.c

## Expected Behavior

code should compileand execute

## Actual Behavior

Code throws error on execution

## Possible Fix

include limits.h

## Steps to Reproduce

compile and execute the code

### PR DESCRIPTION
**Pull request by mainak-debnath**
#### Description of Change
Previously after execution it was throwing error that INT_MIN is not declared. Added limits.h header file to fix that error. 

#### References

Closes #758 
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

File: data_structures/heap/max_heap.c [hunk 1]
```diff
@@ -1,4 +1,5 @@
-#include <stdio.h>
+#include <limits.h> //To define the minimum value for an int
```
Comment (Panquesito7) [inline data_structures/heap/max_heap.c:1]: Please add proper documentation in this line (see #797 as a reference).

File: data_structures/heap/max_heap.c [hunk 2]
```diff
@@ -1,3 +1,8 @@
+/* 
+ * @limits.h defines sizes of integral types.
+ * Constants with the limits of fundamental integral types are defined using this header.
+*/
+#include <limits.h>
```
Comment (Panquesito7) [inline data_structures/heap/max_heap.c:5]: It should be something like this:
```c++
#include <iostream>   /// for IO operations
#include <assert>     /// for assert
```

Comment (mainak-debnath) [reply data_structures/heap/max_heap.c:5]: @Panquesito7 Should I add documentation for all the header files in max_heap.c?

Comment (Panquesito7) [reply data_structures/heap/max_heap.c:5]: For all headers (if possible). Thanks. 🙂

**Review by feartDev — APPROVED** [review]

File: data_structures/heap/max_heap.c [hunk 3]
```diff
@@ -1,5 +1,6 @@
-#include <stdio.h>
-#include <stdlib.h>
+#include <limits.h>  // to define sizes of integral types
+#include <stdio.h>   // for file related input/output functions
+#include <stdlib.h>  // for memory allocation/freeing functions
```
Comment (Panquesito7) [inline data_structures/heap/max_heap.c:3]: What functions do these headers/libraries include that this algorithm/file uses? Document them here.
For example, the `assert.h` library/header provides the `assert` function. In that case, it should be like:
```c
#include <assert.h>   /// for assert
```

**Review by Panquesito7 — APPROVED** [review]
LGTM. Thank you for your contribution! 👍 🎉
